In [ ]:
import numpy as np
x = np.array([1.0,2.0, 3.0])
y = np.array([2.0,4.0, 6.0])

In [5]:
z = x + y # 원소 덧셈
print(z)

[3. 6. 9.]


In [6]:
z = x - y
print(z)
z = x * y
print(z)
z = x / y
print(z)
z = x / 2
print(z)

[-1. -2. -3.]
[ 2.  8. 18.]
[0.5 0.5 0.5]
[0.5 1.  1.5]
